# Generated by Django 4.2.28 on 2026-02-07 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_collaboraterequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaboraterequest',
            name='created_on',
        ),
    ]
